language: php

php:
  - 5.6

env:
  - APPLICATION_ENV=acceptance DB_NAME=test

addons:
  hosts:
    - ora.local
    - oraprojecttest

install:
  - composer self-update

directories:
  - $HOME/.composer/cache/files

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  - phpenv config-rm xdebug.ini

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

    # configure apache virtual hosts
  - sudo cp -f build/ci/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - cp build/ci/.env.example .env

    # Set the GitHub OAuth token to make use of the 5000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp build/ci/.travis.composer.config.json ~/.composer/config.json
  - composer install

  - mysql -e 'create database '"$DB_NAME"';'
  - vendor/bin/doctrine-module orm:schema-tool:create
  - vendor/bin/doctrine-module orm:generate:proxies
  - mysql $DB_NAME < tests/sql/init.sql

  - gem install mime-types -v 2.6.2
  - gem install mailcatcher
  - phpenv config-add build/ci/travis.php.ini
  - mailcatcher

script:
  - cd tests
  - phpunit --configuration unit/phpunit.xml --coverage-text
  - phpunit --configuration integration/phpunit.xml
  - ../vendor/bin/behat --format progress

notifications:
  slack: ideato:lZBegMhS9T81cMvC3PQPrt8u