<p>
IMPORTANT: Possible contribution shifts foreseen within the following days.<br><br>
<?= $member->getDislayedName() ?> has not been fully active in the open governance of <?= $this->organization->getName() ?> in the last <?= $this->withinDays ?> days.<br>
Thus, in order to stay active and keep his current position he will need to have contributed to at least <?= $this->minItems ?> work items where he will have gained at least <?= $this->minCredits ?> credits each, within the next <?= $this->withinDays ?> days.<br><br>
If not complying by that date to this minimum activity, his inactivity will be acknowledged and the the shift from the current position should be put in place by a member, as per current policy in <?= $this->organization->getName() ?>.
</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are part of the "<?= $this->organization->getName() ?>" organization.</p>