<p>
IMPORTANT: Possible contribution shifts foreseen within the following days.<br><br>
You have not been fully active in the open governance of <?= $this->organization->getName() ?> in the last <?= $this->withinDays ?> days.<br>
Thus, if you want to stay active and keep your current position you will need to have contributed to at least <?= $this->minItems ?> work items where you will have gained at least <?= $this->minCredits ?> credits each, within the next <?= $this->withinDays ?> days.<br><br>
If not complying by that date to this minimum activity, your inactivity will be acknowledged and the shift from the current position will be put in place. Then all of your governance accesses and tools will be set to your new level as per current policy in <?= $this->organization->getName() ?>.<br><br>
For any question, please contact a Member of the <?= $this->organization->getName() ?> governance.
</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are part of the "<?= $this->organization->getName() ?>" organization.</p>