<?php $link = $this->router->url($this->host, $this->task); ?>

<p>Hi <?php echo $this->recipient->getFirstname()?>,<br>
    <a href="<?= $link ?>">"<?= $this->task->getSubject()?>"</a> item has an important update: <b><?php echo $this->member->getFirstname()?> <?php echo $this->member->getLastname()?></b> just estimated the item.</p>
<p>Check the estimation progress!</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are an owner of the <a href="<?= $link ?>">"<?= $this->task->getSubject() ?>"</a> item.</p>