<?php $link = $this->router->item($this->task); ?>

<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
time to assign shares "<a href="<?= $link ?>"><?= $this->task->getSubject()?>"</a> item <b>is running out</b>!</p>
<p>Don't miss the chance to tell your taskmates what you think about their contribution.</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the <a href="<?= $link ?>"<?= $this->task->getSubject() ?>"</a> item.</p>