<?php $link = $this->router->item($this->task); ?>

<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
    You haven't estimated <a href="<?= $link ?>">"<?= $this->task->getSubject()?>"</a> item yet!</p>
<p>Do it as soon as possible to define with your taskmate the value of the item.</p>
<p>Welo</p>
<hr>
    <p style="font-size: 12px">You are receiving this e-mail because you are member of the <a href="<?= $link ?>">"<?= $this->task->getSubject() ?>"</a> item.</p>