<?php $link = $this->router->item($this->task); ?>

<p>Hi <?php echo $this->recipient->getFirstname()?>,<br>
    <a href="<?= $link ?>">"<?= $this->task->getSubject()?>"</a> has an important update: <b><?php echo $this->member->getFirstname()?> <?php echo $this->member->getLastname()?></b> just assigned shares to item members.</p>
<p>Check the shares assignment progress!</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are an owner of the <a href="<?= $link ?>">"<?= $this->task->getSubject() ?>"</a> item.</p>