<?php
    $link = $this->router->item($this->task);
    $acceptances = $this->task->getAcceptances();
?>

<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
    the item <a href="<?= $link ?>">"<?= $this->task->getSubject()?>"</a> has been accepted!</p>
<p>
    Here's the recap of the members' votes:
    <table class="summary">
        <thead>
        <tr><th>Member</th><th>Vote</th><th>Motivation</th></tr>
        </thead>
        <tbody>
        <?php foreach($acceptances as $acceptance): ?>
            <?php
                $vote = '';
                switch ($acceptance->getVote()->getValue()) {
                    case 1:
                        $vote = 'voted pro';
                        break;
                    case 0:
                        $vote = 'voted against';
                        break;
                    case 2:
                        $vote = 'abstained';
                        break;
                    case -1:
                        $vote = 'didn\'t vote';
                        break;
                }
            ?>
            <tr>
                <td><?= $acceptance->getVoter()->getFirstname().' '.$acceptance->getVoter()->getLastname(); ?></td>
                <td><?= $vote ?></td>
                <td><?= $acceptance->getDescription(); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</p>
<p>Welo</p>
<hr>
<a style="font-size: 12px">You are receiving this e-mail because you are member of the <a href="<?= $link ?>"<?= $this->task->getSubject() ?>"</a> item.</p>
