<?php $link = $this->router->item($this->task); ?>

<p>Hi <?php echo $this->recipient->getFirstname()?>,<br>
    <a href="<?= $link ?>">"<?= $this->task->getSubject()?>"</a> item has an important update: <b>the user <?php echo $this->user->getFirstname()?> <?php echo $this->user->getLastname()?> has just stopped taking part in it.</b></p>
<p>Check the new item team composition!</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are an owner of the <a href="<?= $link ?>">"<?= $this->task->getSubject() ?>"</a> item.</p>