<?php $link = $this->router->item($this->task); ?>

<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
<?=  $user->getFirstname() . ' ' . $user->getLastname() ?> has been removed from the workitem <b><a href="<?= $link ?>"><?= $this->task->getSubject()?></a></b>.</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are a member of the "<?= $this->organization->getName() ?>" organization.</p>
