<?php $link = $this->router->item($this->task); ?>

<p>Hi <?= $this->recipient->getFirstname() ?>,<br>
the item <a href="<?= $link ?>"><?= $this->task->getSubject()?>"</a> in which you are the owner has NOT been closed automatically, only <?= $this->task->countMembersShare() ?> members on <?= $this->task->countMembers() ?> assigned shares for it!</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are member of the  <a href="<?= $link ?>"<?= $this->task->getSubject() ?>"</a> item.</p>
