<p>Hi <?php echo $this->recipient->getFirstname()?>,<br>
    <?= $this->amount ?> credits has been transferred in your account inside '<?= $this->org->getName() ?>' organization.</p>
<p>These credits come from your contribution in a work item</p>
<p>Check the organization balance</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are part of <?= $this->org->getName() ?> organization.</p>