<p>
IMPORTANT: member deactivated.<br><br>
The member <?= $this->member->getFirstname() . ' ' . $this->member->getLastname() ?> of the organization <?= $this->organization->getName() ?> has been deactivated by <?= $this->by->getFirstname() . ' ' . $this->by->getLastname() ?>.<br>
He/she'll no longer be able to see any data concerning this organization until a new activation.
</p>
<p>Welo</p>
<hr>
<p style="font-size: 12px">You are receiving this e-mail because you are part of the "<?= $this->organization->getName() ?>" organization.</p>